In [1]:
import numpy as np
import pandas as pd


In [ ]:
def sigmoid(x, Derivative=False):
  if Derivative == False:
    return x*(1-x)
  return 1/(1+np.exp(-x))


In [2]:
np.set_printoptions(precision=2)
x = np.array([[0,1,1],
              [0,0,1],
              [1,1,1],
              [1,0,0]])
y = ([[1],
      [0],
      [1],
      [0]])

np.random.seed(1)

#output vectors for neurons(synapses)

a1 = 2*np.random.random((3,4))-1
print(a1)
a2 = 2*np.random.random((4,1))-1
print(a2)


[[-0.17  0.44 -1.   -0.4 ]
 [-0.71 -0.82 -0.63 -0.31]
 [-0.21  0.08 -0.16  0.37]]
[[-0.59]
 [ 0.76]
 [-0.95]
 [ 0.34]]
