In [1]:
import numpy as np
import pandas as pd


In [13]:
def sigmoid(x, Derivative=False):
  if Derivative == True:
    return x*(1-x)
  return 1/(1+np.exp(-x))


In [15]:
np.set_printoptions(precision=2)
x = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
y = ([[0],
      [1],
      [0],
      [1]])

np.random.seed(1)

#output vectors for neurons(synapses)

#a1 = 2*np.random.random((3,4))-1
#print(a1)
#a2 = 2*np.random.random((4,1))-1
#print(a2)
a0 = 2*np.random.random((3,1))-1

for i in range(10000):
  l0 = x
  l1 = sigmoid(np.dot(l0,a0))
  l1error = y - l1
  l1delta = l1error * sigmoid(x=l1, Derivative=True)
  a0+= np.dot(l0.T, l1delta)
  if i%2000 == 0:
    print(l1error)
print(a0)
print(l1)

[[-0.27]
 [ 0.64]
 [-0.24]
 [ 0.67]]
[[-0.02]
 [ 0.01]
 [-0.02]
 [ 0.02]]
[[-0.02]
 [ 0.01]
 [-0.01]
 [ 0.01]]
[[-0.01]
 [ 0.01]
 [-0.01]
 [ 0.01]]
[[-0.01]
 [ 0.01]
 [-0.01]
 [ 0.01]]
[[-0.21]
 [ 9.67]
 [-4.63]]
[[0.01]
 [0.99]
 [0.01]
 [0.99]]
